### ISSUE TITLE
Investigate issues impacting MoJ Forms when pods recycled

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2873] opened 2021-05-11 10:37 UTC
## Service name

MoJ Forms

## Service environment

- [ x] Dev / Development
- [ x] Staging
- [ x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

When pods are recycled this appears to impact MoJ Forms services, causing outages between services which require restarts.

## Problem description

"MoJ Forms team recently reported that during a pod recycled/nodes drained:

The namespaces were fine though, but I think the alert coincided
around the same time as nodes were being drained. A few minutes later
we then had a minor P3 incident where one of our apps stopped being
able to communicate with another app and failed to process jobs as a
result. Restarting those two apps re-enabled communication between
them and they were able to carry on as normal.

The error that is thrown for us is a 403 forbidden which relates to
the public keys for the application either not being accessible or
being incorrect. At this time we are unsure which of those two
specifically."

It appears that when pods are recycled that MoJ Forms is being impacted (we are evidenced this during recent recycles and the service team verified that there were no repeats of the issue when the overnight job was paused).

We want to investigate what is causing these problems. Is it that the process used to drain nodes isn't as graceful as it could be? Is it something to do with daemonsets not being evicted (unless forced)?

Investigate further. See what can be done to improve this situation.

Recent tread - https://mojdt.slack.com/archives/C514ETYJX/p1620379646274600

## Contact person

Matt Tei
Brendan Butler
Tomas Destefi

**Comment by vijay-veeranki** [comment] 2021-05-20 21:01
FB team pointed out that they have seen their tests failing on May 18 2021 01:00:00 AM

Which is caused by this node-recycler job:
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/maintenance/jobs/recycle-node-live-1/builds/22

Kibana event router logs during(18 2021 01:00:00 AM) time filtering on "formbuilder-platform-test-dev" where the tests were running:

https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-18T00:00:00.000Z',to:'2021-05-18T12:05:00.000Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d2f00a00-fbf4-11ea-86fe-a5f65a6b0b79,key:log_processed.event.metadata.namespace,negate:!f,params:(query:formbuilder-platform-test-dev),type:phrase,value:formbuilder-platform-test-dev),query:(match:(log_processed.event.metadata.namespace:(query:formbuilder-platform-test-dev,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d2f00a00-fbf4-11ea-86fe-a5f65a6b0b79,key:log_processed.event.source.host,negate:!f,params:(query:ip-172-20-38-6.eu-west-2.compute.internal),type:phrase,value:ip-172-20-38-6.eu-west-2.compute.internal),query:(match:(log_processed.event.source.host:(query:ip-172-20-38-6.eu-west-2.compute.internal,type:phrase))))),index:d2f00a00-fbf4-11ea-86fe-a5f65a6b0b79,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

There is a event:
**Readiness probe failed: Get http://100.127.52.7:3000/health: dial tcp 100.127.52.7:3000: connect: connection refused**

Kibana kubernetes_cluster logs during(18 2021 01:00:00 AM) time filtering on "formbuilder-platform-test-dev" where the tests were running.

https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-18T00:01:38.000Z',to:'2021-05-18T00:01:50.000Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'89ddb820-d648-11ea-a3d9-7f47a73dbcba',key:kubernetes.namespace_name,negate:!f,params:(query:formbuilder-platform-test-dev),type:phrase,value:formbuilder-platform-test-dev),query:(match:(kubernetes.namespace_name:(query:formbuilder-platform-test-dev,type:phrase))))),index:'89ddb820-d648-11ea-a3d9-7f47a73dbcba',interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

**Comment by vijay-veeranki** [comment] 2021-05-20 21:13
FB team pointed out that they have seen their tests failing on May 19 2021 03:00:00 AM and 05:00:00 AM

Kibana Event logs:

https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-19T02:00:00.000Z',to:'2021-05-19T04:30:00.000Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d2f00a00-fbf4-11ea-86fe-a5f65a6b0b79,key:log_processed.event.metadata.namespace,negate:!f,params:(query:formbuilder-platform-test-dev),type:phrase,value:formbuilder-platform-test-dev),query:(match:(log_processed.event.metadata.namespace:(query:formbuilder-platform-test-dev,type:phrase))))),index:d2f00a00-fbf4-11ea-86fe-a5f65a6b0b79,interval:auto,query:(language:kuery,query:'%22Readiness%20probe%20failed:%22'),sort:!(!('@timestamp',desc)))

**Readiness probe failed: Get http://100.99.95.242:3000/health: dial tcp 100.99.95.242:3000: connect: invalid argument**
**Readiness probe failed: Get http://100.98.246.58:3000/health: dial tcp 100.98.246.58:3000: connect: connection refused**

kubernetes cluster logs:
https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-19T02:00:00.000Z',to:'2021-05-19T04:30:00.000Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'89ddb820-d648-11ea-a3d9-7f47a73dbcba',key:kubernetes.namespace_name,negate:!f,params:(query:formbuilder-platform-test-dev),type:phrase,value:formbuilder-platform-test-dev),query:(match:(kubernetes.namespace_name:(query:formbuilder-platform-test-dev,type:phrase))))),index:'89ddb820-d648-11ea-a3d9-7f47a73dbcba',interval:auto,query:(language:kuery,query:'(%22100.99.95.242%22)'),sort:!(!('@timestamp',desc)))

**Comment by vijay-veeranki** [comment] 2021-05-20 21:38
Assumptions:

This could be solved by increasing the initial delay in the readiness check. Actually, since the connection to the DB was taking more than the initial delay as a result of which the readiness probe was failing.

Suggestion:

Increase the initial delay from 5s to 15sec.

Try rolling update strategy:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/concepts/deploying.html#zero-downtime-deploys

**Comment by vijay-veeranki** [comment] 2021-05-24 09:14
FB team updated the deployment with below changes in "formbuilder-platform-test-dev" namespace.

Increase the initial delay from 5s to 15sec.

Try rolling update strategy:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/concepts/deploying.html#zero-downtime-deploys

**Comment by vijay-veeranki** [comment] 2021-05-24 09:15
FB team confirmed that there are no failures over the weekend on our test runs over the last 3 days.

**Comment by vijay-veeranki** [comment] 2021-05-26 10:40
Will keep this on-hold/blocked for 1 more week, if users don't see any more issues, will close this ticket

**Comment by vijay-veeranki** [comment] 2021-06-10 07:41
FB team noticed issues on all their namespaces on 07th June around 5:10 AM

Node recycle job during that time:
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/maintenance/jobs/recycle-node-live-1/builds/84

Sentry alert showing the alert:
https://sentry.io/organizations/ministryofjustice/issues/2443103096/events/a0dd738852b442f0b0ff895a6ac73e2d/?project=5436220

https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/doc/89ddb820-d648-11ea-a3d9-7f47a73dbcba/kubernetes_cluster-2021.06.08?id=a3vQ6XkBpBPEbabV5bdo&_g=()

**Comment by AntonyBishop** [comment] 2021-07-01 10:42
Hi @vijay-veeranki what is the latest on this ticket?

**Comment by vijay-veeranki** [comment] 2021-07-06 10:30
The user informed that they are a little better once they raised the initialDelaySeconds to 15 on all our apps. But they still get issues though, but they are less and it does still come down to networking connections it seems.

**Comment by vijay-veeranki** [comment] 2021-07-06 11:58
Team tested by adding rolling update strategy
user-guide.cloud-platform.service.justice.gov.uk/documentation/concepts/deploying.html#zero-downtime-deploys

```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
      
```
And ran their acceptance tests
still got ERROR: Could not connect to clamd on fb-av-svc-test-dev: Connection refused

Their apps could not connect to the container running the clamav.

We don't have recycle node running during this time, but still, they have this error, this shows it is not related to node recycler.

**Comment by vijay-veeranki** [comment] 2021-07-08 11:23
We had a call with the Form builder team and discussed the issue more in detail.

Users didn't see the below original issue again:
"When pods are recycled this appears to impact MoJ Forms services, causing outages between services which require restarts."

They did have a network issue, that got better after adding below:
Increase the initial delay from 5s to 15sec.
and 
rolling update strategy:


They still have a connection issue when the ClamAV pod get recycled:

For this form-builder team are going to address this by creating multiple replicas of ClamAV as they only have one replica of it at the moment or use ClamAV as they are using ssh tunnel using open3 at the moment.

The form-builder team are happy to close this ticket and once they sort out the ClamAV, they will reach us if they still see any issue.

**Closed by vijay-veeranki** 2021-07-08 11:23 UTC
Labels: BLOCKED, Support, support team
