### ISSUE TITLE
Check pod limits on nodes on 'live'

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2960] opened 2021-06-11 13:31 UTC
Cope with the 'live' cluster's new limit, due to IP addresses.

'live' cluster has a limit of 20 pods per node. Related to instance type. 
Should we use different instance types?

We are manually changing the number of nodes. Is the number about the same? Redo the calculation in the ADR: https://github.com/ministryofjustice/cloud-platform/pull/2931/files#diff-ae354d90844167143ed3a40d408fedaf4d44d28dd826c3b1d9ffe25d7a773098R130

Need to make sure we have an alert too when we're close to capacity.

**Comment by jasonBirchall** [comment] 2021-06-15 09:16
This is a duplicate of https://github.com/ministryofjustice/cloud-platform/issues/2951

**Comment by davidread** [comment] 2021-06-15 09:32
Some overlap yes, but not the same, I think

**Comment by sablumiah** [comment] 2021-06-18 15:57
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1252

**Closed by sablumiah** 2021-06-18 15:57 UTC
