### ISSUE TITLE
UPGRADE FAILED: timed out waiting for the condition

### ISSUE THREAD

**Issue by reggieb** [ministryofjustice/cloud-platform#674] opened 2019-02-25 10:22 UTC
## Service name

LAA Apply for legal aid (laa-apply-for-legalaid)

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [x] Other

UAT failure

## Impact on the service

We are getting time out failures deploying to UAT. This is preventing work being review and is therefore halting our development process.

## Problem description

On deployment to UAT the following failure is occurring: 

```
Deploying CIRCLE_SHA1: 1ce6fdf62c54bc2a55fb9eff2fb046376197300c under release name: 'apply-for-legal-aid-ap-185-identify-types-of-incom'...
Error: UPGRADE FAILED: timed out waiting for the condition
Exited with code 1
```
See https://circleci.com/gh/ministryofjustice/laa-apply-for-legal-aid/3216?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

This is linked to this PR: https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/301

I have rerun the the workflow and got the same (failure) result.

## Contact person

Rob Nichols. Slack: RobNichols

**Comment by razvan-moj** [comment] 2019-02-25 12:09
closing as duplicate of #604

**Closed by razvan-moj** 2019-02-25 12:09 UTC
Labels: support team
