### ISSUE TITLE
Alert if CircleCI queue size gets too big, during working hours

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#895] opened 2019-05-08 09:26 UTC
Note: This might involve writing a Prometheus exporter for CircleCI.

This Jenkins exporter might be useful, for inspiration: https://github.com/lovoo/jenkins_exporter

## Service name

CircleCI

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

If CircleCI queues get too large, deployments may be delayed by an unacceptable amount.

## Problem description

Many (most?) of our production services depend on CircleCI for continuous deployment.

The LAA [have just adopted CircleCI](https://github.com/ministryofjustice/laa-architecture-documentation/pull/18)
as their default CI/CD tool for all of their services. This is going to lead to an increase in the number
of jobs going through the service.

We are not monitoring the size of the queues on CircleCI, so if there were to be a problem, we wouldn't
know about it until it affected our users.

## Definition of done

 - [ ] We are gathering metrics from CircleCI
 - [ ] We will be alerted if the CircleCI queue size rises above a threshold during working hours
 - [ ] We will not be alerted if the CircleCI queue size breaches the threshold outside working hours

**Comment by AntonyBishop** [comment] 2019-05-08 09:41
@digitalronin. What is the purpose of the alert? Will we be taking action as a result of the alert? Do we own the CircleCI pipelines? I'd want to be careful if we start monitoring and alerting on 3rd party pipelines and we might end up taking on responsibility for fixing them.

Is this more about duty of care to just inform users of issues rather than fixing them?

**Comment by digitalronin** [comment] 2019-05-08 11:04
> Is this more about duty of care to just inform users of issues rather than fixing them?

I was thinking exactly this, yes. 

If the CircleCI queues start backing up, then either;

 * A. CircleCI themselves are having problems, or
 * B. We need more capacity

If it's A, we just have to notify people (probably via #cloud-platform-update).

If it's B, we notify Steve and he gets the credit card out!

**Comment by AntonyBishop** [comment] 2019-05-08 11:07
That's great. Thanks for clarifying.

**Comment by pwyborn** [comment] 2019-05-28 08:21
This maybe inspiration too? https://github.com/grupozap/circleci-exporter

**Comment by pwyborn** [comment] 2019-06-03 14:36
At the moment "Insights" in CircleCi seems to be on a project by project basis:

Email From CircleCi (required metrics do not appear to be available  at the moment):

Hello Paul,

We have a product called Insights, I provided a link below. Does this meet your needs?

https://circleci.com/docs/2.0/insights/

We are also developing an API specifically for analytics. Keep an eye out on our announcement page for more information on that in the near future. https://discuss.circleci.com/c/announcements

**Comment by digitalronin** [comment] 2019-06-03 14:41
IIRC, Insights shows you "your" projects, where (I think) "your" == you follow the project on github

I don't think it's much use to us. It seems very targeted at individuals/small teams with just a few CI projects on the go.

**Comment by pwyborn** [comment] 2019-06-04 07:57
Hi Scott,
	Thank you for your reply - I think the insights is good for investigating on the dashboard - however I would like to extract data for the reasons shown below (prometheus alarms over whole org), Sorry Scott I have the following follow up questions please:

The reason for my request is that we wish to output to Prometheus which will intern alert us if the CircleCI build queue is above a certain size across the organisation (and therefore potentially problems). Do you think that is possible?

We would also like to analyse the mean time for builds across the organisation - again to output to Prometheus and alert if it goes above a certain time (indicating a problem)?

This project (https://github.com/grupozap/circleci-exporter) suggests that metric are available for status “circleci_last_build_status” (although this would appear to be on a project by project basis. Is there a list of status and metrics available please?

Is there a way of getting a CIRCLE_TOKEN for the whole org rather than a specific project, if so how is it created/accessed and is that only for admin users?




Paul Wyborn
Senior WebOps Engineer
Cloud Platforms | Justice Digital & Technology
10.54 Tower (Orange Core)

mailto:paul.wyborn@digital.justice.gov.uk

**Comment by pwyborn** [comment] 2019-06-04 08:01
@digitalronin. Hi saw your comments after I had sent the email for additional information. Think I have said the same kind of thing to them in my garbled language

**Comment by pwyborn** [comment] 2019-06-04 08:10
Just as a matter of interest I received the following email from CircleCI on the 10th of April (not sure if others got it or not?). It explains reasons for decreased performance in general in recent times:

"Hi Paul, 

Over the past few days, our reliability has not met our standard of excellence. We are writing to apologize for any disruptions this may have caused for you and your work. Resolving these issues is our team’s top priority, and we are doing everything we can to resume the level of service you expect from CircleCI. 

What happened: 

The majority of recent incidents are related to an unexpectedly high increase of jobs processed on our platform. This new level of requests has caused one of our primary datastores to be much slower than normal, and at times, unresponsive. These datastore issues have resulted in slow or stopped job processing for some customers. 

What we are doing to resolve these ongoing issues: 

Historically, we have been able to plan and support the ongoing growth of our platform through predictable scaling of this datastore. In this instance, however, we have witnessed 10-100x increases in latency and complete datastore stalls. We are working closely with the datastore technology provider to tune the datastore itself and adapt our own application code to make optimal use of the datastore. 

Where to learn more:

We will release a full root cause analysis when we have observed a sufficient period without further datastore incidents. When we do so, you will be able to find it on our Status Page, and we will also link to it on Discuss here.  

Thank you for your continued patience and support. We know that your CI/CD pipelines are a mission-critical part of the work your team does. We are committed to being as transparent as we can, and apologize again for any impacts you and your team have felt. 

Sincerely, 

The CircleCI Team

**Comment by pwyborn** [comment] 2019-06-10 08:56
Kyle Tryon (CircleCI)
Jun 7, 06:31 PDT

Request #52377 "Metrics" was closed and merged into this request. Last comment in request #52377:

Hello Paul,

<b>It's not possible to output analytics on builds</b>. If this is a feature you would like to see at CircleCI, please submit a feature request at the link below:

[https://ideas.circleci.com/ideas](https://ideas.circleci.com/ideas)

The Github project you linked is not supported by CircleCI. We can't support or guarantee its functionality. However, we do have API functionality to report on the last build status. You can find more information on that here: https://circleci.com/docs/api/#get-all-followed-projects

CIRCLE_TOKEN is usually a personal API key, more information can be found here: https://circleci.com/docs/2.0/managing-api-tokens/#creating-a-personal-api-token

Please let us know if you have any more questions, happy building!

Scott Wheeler
Support Engineer @ CircleCI

**Comment by pwyborn** [comment] 2019-06-10 08:59
It is not possible to output analytics on builds at the present time (email from CircleCI above)

**Comment by digitalronin** [comment] 2019-07-01 14:36
Now that we have circleci stats being logged to elasticsearch, it should be possible to continue with this ticket.

Related to #1039

**Closed** 2019-10-21 15:02 UTC
Labels: Support
