### ISSUE TITLE
Firebreak idea: Install CloudWatch Prometheus exporter

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#980] opened 2019-06-06 11:19 UTC
## Background

At the moment we have no visibility on things like RDS instance reliability. I propose we install the cloudwatch exporter for prometheus (below), which allows users/us to create triggered alerts (via the prometheusRules CRD) and inform teams slack channels. 

There are a few things to think about here: How does the prom alert know how which DB instance to query??

https://github.com/prometheus/cloudwatch_exporter

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment] 2019-06-12 14:35
Duplicate of Add CloudWatch to Prometheus exporter #823

**Closed by AntonyBishop** 2019-06-12 14:35 UTC
