### ISSUE TITLE
C100 dev environment setup

### ISSUE THREAD

**Issue by zaparka** [ministryofjustice/cloud-platform#6206] opened 2024-09-27 14:17 UTC
## Service name
Family Justice C100 Service

C100 

## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service
When developing new tickets we need an easy way to deploy PRs to a dev environment. Currently the production (master) is full of tickets that needs approvals which creates backlog. 

## Problem description
https://github.com/ministryofjustice/c100-application/pull/1674

I was advised to create a dev environment so we can use it for our testing. I managed to merge PR https://github.com/ministryofjustice/cloud-platform-environments/pull/26132  and  
https://github.com/ministryofjustice/cloud-platform-environments/pull/26199

which created the dev environment. But our project doesn't support the standard deploy route described here
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/deploying-an-example-application.html#deploying-an-example-application

So I'm updating our CI config file where the deployment is managed. I got to the point where kubectl set image is failing due to "Unable to connect to the server: dial tcp: lookup c100-application-dev on 127.0.0.11:53: no such host" error inside CI build 

https://app.circleci.com/pipelines/github/ministryofjustice/c100-application/3976/workflows/183958d2-5f88-4cf1-ae7f-2643e5c7592f/jobs/7538?invite=true#step-103-17

I would like to request official help so we can sort this out faster. 

## Contact person
Petr Zaparka
petr.zaparka@hmcts.net / petr.zaparka@digital.justice.gov.uk
Petr Zaparka on slack

**Comment by zaparka** [comment] 2024-10-02 09:37
PR in app deploy repo https://github.com/ministryofjustice/c100-application-deploy/pull/118

**Comment by timckt** [comment] 2024-10-08 14:54
As discussed the problem is in the application pipeline.

We can see there is `This job was rejected because the image 'ubuntu-2004:202107-02' is [unavailable](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/)` which the image in depreciated.
![Image](https://github.com/user-attachments/assets/e5e6abd9-ed07-4076-853b-c55edb71a85a)


We tried to update the aws-ecr orb from `8.2.1` to `9.3.4` and this time the ubuntu error is gone.

**Comment by timckt** [comment] 2024-10-09 10:24
As discussed the problem is in the application Circle CI pipeline.

We can see there is This job was rejected because the image 'ubuntu-2004:202107-02' is [unavailable](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/) which the image in depreciated.
![Image](https://github.com/user-attachments/assets/a5c45bf0-7fa3-4ad3-ae99-a6842eb2b158)

**Comment by timckt** [comment] 2024-10-09 10:51
It appears that the problem is related to the CircleCI pipeline in the application and not the Cloud Platform infrastructure. As a result, I'll be closing this ticket from our side.

If any Cloud Platform infrastructure support is needed in the future, feel free to reach out.

**Closed by timckt** 2024-10-09 10:51 UTC
Labels: support-team
