### ISSUE TITLE
Increased incidence of IOError after ingress controller change

### ISSUE THREAD

**Issue by exonian** [ministryofjustice/cloud-platform#799] opened 2019-04-08 09:31 UTC
## Service name

cla_public

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

None identified as yet.
The errors come after the client closes the connection but uwsgi isn't aware so tries to use it still, so it's quite possible that the connections are being closed legitimately as before and the difference is that now uwsgi isn't finding out (as opposed to the change being that connections are being closed more quickly than before).

## Problem description

We've seen a significant increase (from basically none) in incidents of what we think is uwsgi trying to use a pipe/socket that nginx has already closed. It seems to correspond with the ingress controller change from last Tuesday.
[Kibana logs](https://kibana.apps.cloud-platform-live-0.k8s.integration.dsd.io/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2019-04-01T15:41:55.827Z',mode:absolute,to:'2019-04-08T08:41:41.917Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ec9109a0-2b35-11e9-ac82-95e56bd45b02,key:kubernetes.labels.app,negate:!f,params:(query:laa-cla-public-app,type:phrase),type:phrase,value:laa-cla-public-app),query:(match:(kubernetes.labels.app:(query:laa-cla-public-app,type:phrase))))),index:ec9109a0-2b35-11e9-ac82-95e56bd45b02,interval:auto,query:(language:lucene,query:'closed%20pipe'),sort:!('@timestamp',desc)))

## Contact person

Michael Blatherwick
@MichaelBlatherwick 
michael.blatherwick@digital.justice.gov.uk

**Comment by sldblog** [comment] 2019-04-15 14:39
Update: from Kibana, it seems the broken pipes have significantly increased on 2 April 2019:

<img width="1720" alt="Screen Shot 2019-04-15 at 15 37 09" src="https://user-images.githubusercontent.com/1526295/56141260-62dd9c80-5f94-11e9-9bcb-7ec4d8116673.png">

"siginificantly" in this instance means going from 5 events / day &rarr; 60-140 events / day.

**Comment by razvan-moj** [comment] 2019-05-15 10:54
Hi - this is still ongoing at similar rates; references I found to this error message suggest it is a normal client disconnect which was not visible before because the AWS ALB was handling the TLS part. @sldblog ca you please doublecheck if this is an error or just a warning that should be muted in Django's config?

**Comment by kcbotsh** [comment] 2019-05-29 09:03
@sldblog please see comment above from @razvan-moj. Does this issue still need investigation  or would it be ok to close this issue? 

thanks

**Comment by sldblog** [comment] 2019-05-29 09:51
Thanks for the ping @kcbotsh.

@razvan-moj: You are right; I strongly suspect disconnects are the case. I will try and reproduce with a test and will mute the errors if it confirms that due to the new setup we now get these events.

**Comment by sldblog** [comment] 2019-05-29 16:31
It looks like https://stackoverflow.com/a/40375474/621923 might be what is happening here.

I can see 499 responses by nginx. The number of 499 responses correlate to "broken pipe" messages from uwsgi. Sentry, unfortunately, does not report all of these occurrences, but I'm satisfied client disconnects cause this.

Happy to close, thank you :tada:

**Closed** 2019-05-30 19:05 UTC
Labels: support team
