### ISSUE TITLE
Replace Zenhub with GitHub Projects and GitHub Actions

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2065] opened 2020-07-13 15:19 UTC
We currently use Zenhub to manage GitHub issues across multiple repositories with the kanban board feature. The Zenhub interface leaves a lot to be desired. Is there a way we can utilise GitHub's [project management](https://github.com/features/project-management/) along with a few GitHub actions to remove the need for Zenhub.

Create a project in the [main Cloud Platform repository](https://github.com/ministryofjustice/cloud-platform/projects) and link issues with every cloud-platform-* repository. Create an action to automatically place a support label on support issues and any others you can think of.

**Comment by digitalronin** [comment] 2020-08-20 08:36
I've been looking into this. A few initial thoughts:

## Issues

The easiest way to handle this would be to have a rule that *all* cloud platform issues are raised against *this* repository - i.e. if there's an issue relating to the CLI, we raise it and manage it in this repo, not any of our other repos.

If we can live with this, we can do a one-off import of any outstanding issues from our other repos to here (I've already got most of the scripts written to automate this), and then turn off the "issues" feature on all our other repos (we can easily automate that step, too).

## Story points

There is no native support for a numeric value on github issues, so we would have to use magic labels such as "size:1", etc. That's pretty simple.

Adding up story points is slightly more complicated. Given a set of magic labels, it's easy enough to automate, but it wouldn't necessarily happen in realtime, as we move issues from one project board column to another, and open/close issues.

I'm sure we can automate the process of adding up all the points in a column and storing that info somewhere (maybe in a special card that always stays at the top of each column), but however we do it, there would be some lag between making the change and seeing the points total. Similarly, we would need to build some way of adding up all the story points matching a search (e.g. add up all the story points in the "backlog" column where the issue has the label "next sprint").

This is all doable, but it's not going to work as smoothly as it does with zenhub right now, so the question is whether or not we can accept a bit of clunkiness in this area if it means we can get rid of zenhub.

## Devils' Advocate

If we make the change to have *all* issues in the cloud-platform repo, then the argument for moving away from zenhub becomes less compelling. The main drawback to zenhub is how long it takes to load up the board and open up different issues. If we know the issue is visible on [this page](https://github.com/ministryofjustice/cloud-platform/issues) then those of us who dislike the zenhub interface can simply stick to the github web interface.

**Comment by AntonyBishop** [comment] 2020-08-20 12:59
Couple of question:

- What does option 2 gain us?

- What is the good practice position on raising issues against a single repo? (I only ever use the one anyway, but that is because I tend to raise my issues via Zenhub).

In terms of my needs, Projects allows me as a PM to create, prioritise, track and view work. It ticks those boxes.

My concern is that reporting elements are not there and that would be some manual hacking around of data in some other tooling. This is less appealing. Perhaps we need to drill into these needs more to see what is available in Projects.

**Comment by digitalronin** [comment] 2020-08-20 14:45
I see option 2 as quite a decent middle ground, because it makes it easier for me to find a give issue without having to launch zenhub at all - I can just visit the main [issues page](https://github.com/ministryofjustice/cloud-platform/issues) and use the search capabilities of github. 

I can't do that right now because the issue could be on any of (currently) 9 different repos, so zenhub is the only practical way to search for an issue.

The previous point brings up another gripe I have about zenhub, which is that adding a new repository as a source of issues is quite tedious. Switching to a single repo for all issues would get around that, as well.

**Comment by digitalronin** [comment] 2020-08-24 13:28
Parking this as blocked until Karen comes back from holiday. I think she should be involved in any decisions we make about this.

**Comment by AntonyBishop** [comment] 2020-09-07 11:58
Unblocking to revisit now that Karen has returned.

**Comment by AntonyBishop** [comment] 2020-09-10 09:19
Hi @kcbotsh 

Following discussion yesterday it feels like there is little value in pursuing the change to move to GitHub projects as an alternative to ZenHub. 

Use of GitHub projects would require a bunch of changes to provide the simplest standard features of a Kanban tool e.g. estimating, reporting of work flow. That feels like a lot of effort to address slow performance of ZenHub.

My recommendation would be to close this issue for now and revisit if the GitHub Projects feature set changes in the future. We could of course raise an issue with GitHub to add this feature.

Grateful for your views. Cheers.

**Comment by digitalronin** [comment] 2020-09-10 10:21
I agree with ☝️ , but I would like us to consider a policy where all tickets on our backlog exist in the main "cloud-platform" repo, as opposed to be scattered across multiple repos.
i.e. continue to use zenhub, but only have one repo "feeding in" to it.
The benefit is that it would make it easier for the team to search for, view and edit tickets without having to go through the slow and painful zenhub UI.

**Comment by AntonyBishop** [comment] 2020-09-16 09:57
Thanks @digitalronin. I'm ok with that. Some questions.

1. How to we enforce that?
2. Do we migrate issues to the same repo, or do we just start from new issues after a given point of time?

**Comment by digitalronin** [comment] 2020-09-18 16:24
Sorry, I didn't see your comments, Tony:

1. If we only show issues from the cloud-platform repo in Zenhub, it pretty much enforces itself in the sense that if you raise a PR on another repo, we probably won't see it, although we can also disable the "issues" feature on all our other repos, in their settings.
2. We can migrate all the issues - it wouldn't be too hard to do this with a script. I think I already looked at this, and have the bones of one.

**Comment by AntonyBishop** [comment] 2020-09-23 10:02
Decided not to pursue replacement. Will look at migrating issues to a single repo (#2357)

**Closed by AntonyBishop** 2020-09-23 10:02 UTC
Labels: Support
