### ISSUE TITLE
Upgrade helm to 3.xx

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1172] opened 2019-08-16 13:03 UTC

**Comment by AntonyBishop** [comment] 2020-02-13 14:53
Now it is officially released support for helm 3 for the terraform helm provider. It means we should upgrade our components to use helm 3 with the terraform provider.

**Comment by AntonyBishop** [comment] 2020-02-13 14:53
Duplicate of #1172

**Closed** 2020-05-26 09:28 UTC
Labels: Support
