### ISSUE TITLE
Fluentd-es - Stop duplication of backlog

### ISSUE THREAD

**Issue by ollieanwyll** [ministryofjustice/cloud-platform#301] opened 2018-08-07 11:09 UTC

**Comment by alkar** [comment] 2018-08-08 11:15
The config file already defines [`pos_file`](https://docs.fluentd.org/v0.12/articles/in_tail#pos_file-(highly-recommended)) paths that are on the host machines (see the `DaemonSet` `volumes`) so in theory this shouldn't happen. The files persist after `fluentd` is de-provisioned so it should be able to pick up from where it left.

**Comment by alkar** [comment] 2018-08-30 11:28
This is because I've done 2-3 `rolling-updates` since yesterday which wipes nodes. `fluentd` hasn't been allowed to run since then, hence files are missing.

**Comment by razvan-moj** [comment] 2018-08-30 11:31
so it's working as intended; will doublecheck the _pos files show up after reinstall and close this

**Comment by alkar** [comment] 2018-08-30 11:58
I'm hoping so. @ollieanwyll, however, noticed this odd behaviour. I suppose this ticket is blocked at the moment, as I work through the 1.11 upgrade issues.

**Comment by razvan-moj** [comment] 2018-09-03 13:01
![fluentd - es.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5af95cb3f4ddc900131b5a50/125516c66e82c728ace21e0d46ee988f268c97adcfa4ff46b71fbcd6395428792c07b7692ac7b629b91779540d584eae48585c40fcf98b2ef0e53e76dc0919f1c32f0e2a92624cf5f2d75dad0ba821834584b3bf8f45c7e13b24e48d8f472c53.png)

after a daemonset delete/redeploy, _pos files are kept and uploads resume as expected

**Closed** 2018-09-03 13:01 UTC
Labels: in progress
