### ISSUE TITLE
Investigate large number of HTTP 499 errors

### ISSUE THREAD

**Issue by mattops** [ministryofjustice/cloud-platform#4976] opened 2023-11-13 13:27 UTC
## Service name

All services hosted in the CP live cluster.

## Service environment

All

## Impact on the service

Possible poor user experience and unreliable service-to-service http requests.

## Problem description

Seeing a large number of 499 http errors reported in the ingress-nginx access logs.

[kibana logs here](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h,to:now))&_a=(columns:!(log_processed.request_uri,log_processed.status,log_processed.http_host,log_processed.request_time),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'8a728bc0-00eb-11ec-9062-27aa363b66a2',key:log_processed.status,negate:!t,params:(query:499),type:phrase),query:(match_phrase:(log_processed.status:499)))),index:'8a728bc0-00eb-11ec-9062-27aa363b66a2',interval:auto,query:(language:kuery,query:''),sort:!()))

**Comment by pwyborn** [comment] 2023-11-14 09:22
499:
Not a standard http status code. Wide ranging code
It is used by the Nginx Server to indicate that the client closed before the server could respond.
The client is not necessarily the user.
In some cases the error may be caused by a misconfigured server or network issue that disrupts the connection between the client and the server,
https://www.webfx.com/web-development/glossary/http-status-codes/what-is-a-499-status-code/

**Comment by pwyborn** [comment] 2023-11-14 09:26
Network issues:
If there is a problem with the network connection between the client and server, such as a dropped connection or high latency, the connection may be lost before the server can respond.

Client-side issues:
If the client navigates away from the page before it fully loads, or cancels the request before the server can respond, the connection may be terminated before a response is received.

Server-side issues:
If the server is experiencing issues, such as a high load or a misconfiguration, it may be unable to respond to the client’s request in a timely manner.

Firewall or security software:
If there is a firewall or security software in place that is blocking the connection or interfering with the communication between the client and server, the connection may be lost.

Misconfigured server:
If the server is misconfigured, it may not be able to properly handle requests and may result in a 499 error.

Server-side timeout:
The server may have a configuration that sets a timeout period for the response, and if it exceeds the limit, it may close the connection and result in a 499 error.

These are just a few examples of what could cause an HTTP 499 error. In order to determine the specific cause of the error, it may be necessary to investigate further using server logs or other troubleshooting methods.

**Comment by pwyborn** [comment] 2023-11-14 09:32
Kibana:
https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1M%2FM,to:now))&_a=(columns:!(log_processed.request_uri,log_processed.status,log_processed.http_host,log_processed.request_time,log_processed.kubernetes_namespace),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'8a728bc0-00eb-11ec-9062-27aa363b66a2',key:log_processed.status,negate:!f,params:(query:499),type:phrase),query:(match_phrase:(log_processed.status:499)))),index:'8a728bc0-00eb-11ec-9062-27aa363b66a2',interval:auto,query:(language:kuery,query:''),sort:!())

**Comment by pwyborn** [comment] 2023-11-14 09:33
Slack ask original question:
https://mojdt.slack.com/archives/C57UPMZLY/p1699882357679199

**Comment by pwyborn** [comment] 2023-11-15 09:48
It seems to be across more than 1 namespace (which maybe points to the client closed connections not being the user and maybe server or network based?)
Matt has has said this has been going on for some time (maybe years).
2 amongst many possible causes/suggestions is:

1 - https://julianli.co/articles/kubernetes-probes-cause-nginx-http-499-error Increasing timeout seconds on liveness and readiness probes (there are some failures of both across all namespaces ` k describe pods -A | grep -i failure`.
In here they increased theirs from 1 to 5 (the ingress-controllers namespace timeout probes are already set to 5s).
I need to investigate the implications of increasing the timeout further.

2 - https://bobcares.com/blog/aws-elb-nginx-499/#:~:text=In%20case%20the%20Server%20is,AWS%20ELB%20Nginx%20499%20response Setting the loadbalancer timeout which by default is is set to 60 seconds. You are supposed to be able to change this on the AWS console under "attributes" for the loadbalancer. I cannot find anything this setting - do I therefore assume that it is defaulting to 60 seconds, and that we would actually need to set it up in our config somewhere?

**Comment by pwyborn** [comment] 2023-11-15 11:56
Also worth looking at?:
https://kubernetes.io/blog/2019/03/29/kube-proxy-subtleties-debugging-an-intermittent-connection-reset/

**Comment by pwyborn** [comment] 2023-11-21 09:29
"digital-prison-services-prod" seems to have significantly more 499s than other namespaces (+ 2 others), which seems to suggest namespace configuration as a possible cause? See https://mojdt.slack.com/archives/C57UPMZLY/p1700062949745829?thread_ts=1699882357.679199&cid=C57UPMZLY - discussions with user.
I am going to close this issue, however to be re-oppened if evidence to the contrary comes up.

**Closed** 2023-11-23 09:45 UTC
Labels: support team, Environments
