### ISSUE TITLE
Further investigate the KubeAPILatencyHigh alarm

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1544] opened 2019-12-27 16:29 UTC
The cluster seems to be frequently faced with the :`KubeAPILatencyHigh` alarm. 
The latest occurence can be found here : [slack thread](https://mojdt.slack.com/archives/C8QR5FQRX/p1577462890001000)

This seems to be loosely related to the integration tests, and the spike of API call they produce.

Further investigation required.

**Comment by jasonBirchall** [comment] 2020-01-20 11:47
There is a theory that this issue is caused by the integration tests spamming the API server. We have taken the action to pause the integration test pipeline, which runs hourly. If the KubeAPILatencyHigh alarms persist, we can officially rule out this theory. Update to follow shortly.

**Comment by jasonBirchall** [comment] 2020-01-21 10:25
https://github.com/ministryofjustice/cloud-platform/issues/1598

**Comment by digitalronin** [comment] 2020-01-23 10:07
So far, this seems to be closed by https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/553

**Closed by digitalronin** 2020-01-23 10:07 UTC
Labels: enhancement, needs-triage
