### ISSUE TITLE
Prometheus queries report "Error executing query: error" when user session times out

### ISSUE THREAD

**Issue by solidgoldpig** [ministryofjustice/cloud-platform#573] opened 2019-01-03 11:48 UTC
## Service name

Prometheus web interface
https://prometheus.apps.cloud-platform-live-0.k8s.integration.dsd.io/graph

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x ] Prod / Production
- [ ] Other

## Impact on the service

Confuses users (this user at least)

## Problem description

Prometheus web interface silently times out - any attempt to execute queries after that happens result in a cryptic "Error executing query: error" message.

Logging back in makes the problem go away, but it took me some time to realise that was the problem - I presume this is actually just a Prometheus issue and it's hardly a show stopper.

## Contact person

Alex Robinson @alex.robinson

**Comment by solidgoldpig** [comment] 2019-01-03 11:48
<img width="412" alt="prometheus_time_series_collection_and_processing_server" src="https://user-images.githubusercontent.com/4856/50636307-77e67080-0f4d-11e9-8b52-c3978c3259bb.png">

**Comment by jasonBirchall** [comment] 2019-01-29 18:05
Duplicate of https://github.com/ministryofjustice/cloud-platform/issues/573.

**Closed by jasonBirchall** 2019-01-29 18:05 UTC
Labels: in progress
