### ISSUE TITLE
Document ways for teams to add authentication at ingress level

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#923] opened 2019-05-20 08:52 UTC
## Background

For 'dev' namespaces, teams might want to have authentication before any request reaches the actual apps, and the nginx ingress looks like a good place to add this.

## Approach

 - Test the supported auth methods (Basic? OAUTH?)
 - Check if this conflicts with generally-used form-based auth in the apps
 - Update user guide

## Definition of done

- [ ] user docs have been updated
- [ ] notification in cloud-platform-update

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by digitalronin** [comment] 2019-05-20 09:26
FWIW, I would focus on basic auth, initially.

The main reason teams need some authentication in front of dev. namespaces is because they're exposed on a *.gov.uk domain, and the guidelines say we need to do something to prevent members of the public from using things which they might believe are live, production services.

So, I think this is more of a checkbox feature than something teams really want to spend a lot of time and energy on. As long as they can create a (team-shared) set of credentials to keep random people from using the dev. apps, that's all they'll need, IMO.

cf. 6) Set a username and password on this page of the gov.uk prototype kit docs:

https://govuk-prototype-kit.herokuapp.com/docs/publishing-on-heroku

**Comment by alkar** [comment] 2019-05-21 14:23
Duplicate of #917

**Closed** 2019-08-08 13:10 UTC
Labels: Support
