### ISSUE TITLE
Stop manually applying Terraform

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2235] opened 2020-08-18 10:04 UTC
Placeholder for discussion

**Comment by davidread** [comment] 2020-11-25 11:16
Duplicate of https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2446undefined

**Closed** 2020-11-26 15:39 UTC
Labels: EPIC, needs-triage
