### ISSUE TITLE
Github action to reject a PR if it references out of date terraform module

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1823] opened 2020-04-22 13:58 UTC
As part of the HOODAW app. we have ruby code to find the latest version of any of our terraform modules. We can use this to create a github action which looks for references to any of our terraform modules in the source code, and rejects the PR if it's using a version that isn't the latest one.

**Comment by mtrbls** [comment] 2020-04-29 10:52
Could we simply delete old releases of the terraform modules ? 
Would terraform plan fail if the module's `source` does not exist ?

**Comment by AntonyBishop** [comment] 2020-05-27 14:58
Duplicate of #1556

**Closed by AntonyBishop** 2020-05-27 14:58 UTC
Labels: Firebreak
